-- MedLink LIS: Dictionaries - Supported Analyzer Types & Protocols
-- Generated for PostgreSQL (MedLink evomis)

INSERT INTO lab_analyzer_types (id, code, name, note, config, is_active) VALUES
  (1, 'SYSMEX XS-1000I', 'Sysmex XS-1000i', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (2, 'СOBAS 411', 'Сobas 111', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (3, 'VITROS', 'Vitros', 'Vitros 5600,4600,3600,XT7600,XT3400', '{"exch_type": "ASTM"}'::jsonb, true),
  (4, 'VITROS EVIQ', 'Vitros EViQ', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (5, 'AUTOVUE INOVA', 'AutoVue Inova', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (6, 'URISYS', 'Urisys 1100', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (7, 'STAGO START', 'Stago start', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (8, 'REFLOTRON', 'Reflotron', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (9, 'BIOKSEL', 'Bioksel', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (10, 'TOSO', 'TOSO', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (11, 'COBAS311', 'COBAS 311', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (12, 'COBAS411', 'COBAS 411', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (13, 'SYSMEX2000', 'SYSMEX2000', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (14, 'COBAS111', 'COBAS 111', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (15, 'INTEGRA', 'INTEGRA', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (16, 'GEM4000', 'GEM 4000', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (17, 'SYSMEXSUIT', 'SYSMEXSUIT', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (18, 'SYSMEX2500', 'SYSMEX2500', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (19, 'SYSMEXCA600', 'SYSMEXCA600', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (20, 'CLINTEC', 'CLINTEC', NULL, '{"eop": "DQ==", "exch_type": "TEXT"}'::jsonb, true),
  (21, 'PENTRA', 'PENTRA', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (22, 'ABL80', 'RADIOMETER ABL80', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (23, 'AQT90', 'RADIOMETER AQT90', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (24, 'SIEMENS', 'SIEMENS VANTAGE', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (25, 'BIOSYSTEMA15', 'BIOSYSTEM A15', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (26, 'NIHON9100', 'Nihon 9100', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (27, 'HUMACOUNT5D', 'Huma Count 5D', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (28, 'HUMACOUNT5L', 'Huma Count 5L', NULL, '{"bop": "AQ==", "eop": "BA==", "exch_type": "HUMA5L", "full_text": 1, "control_sum": 1}'::jsonb, true),
  (29, 'MAGLUMI', 'MAGLUMI', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (30, 'HUMASTAR', 'Huma Star', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (31, 'PRESTIGE', 'PRESTIGE', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (32, 'SYSMEXXN', 'SYSMEXXN', NULL, '{"exch_type": "ASTM_ASK"}'::jsonb, true),
  (33, 'MINDRAY', 'MINDRAY', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (34, 'ACCESS', 'ACCESS', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (36, 'BECKMAN', 'BECKMAN', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (37, 'MINDRAYBS30', 'MINDRAYBS30', NULL, '{"exch_type": "HL7"}'::jsonb, true),
  (38, 'MINDRAY240', 'MINDRAY240', NULL, '{"exch_type": "HL7"}'::jsonb, true),
  (39, 'MINDRAY3100', 'MINDRAY3100', NULL, '{"exch_type": "HL7"}'::jsonb, true),
  (40, 'VITROS5600', 'VITROS5600', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (41, 'ACLTOP300', 'ACLTOP300', NULL, '{"sleep": 500, "exch_type": "ASTM", "control_sum": 1}'::jsonb, true),
  (42, 'URILYZER100PRO', 'URILYZER100PRO', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (43, 'BECKMANCOULTER500', 'BECKMANCOULTER500', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (44, 'WONDFOFINECARE', 'WONDFOFINECARE', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (45, 'CYAN', 'CYAN', NULL, '{"exch_type": "CYAN"}'::jsonb, true),
  (46, 'UWAM', 'UWAM', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (47, 'BIOSYSTEMS', 'BIOSYSTEMS', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (48, 'JUNIOR', 'JUNIOR', NULL, '{"exch_type": "JUNIOR"}'::jsonb, true),
  (49, 'ACCESS2', 'ACCESS2', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (50, 'UC1000', 'UC-1000', NULL, '{"bop": "Ag==", "eop": "Aw==", "exch_type": "UC1000"}'::jsonb, true),
  (51, 'ABL9', 'RADIOMETER ABL9', NULL, '{"bop": "AQ==", "exch_type": "ASTM"}'::jsonb, true),
  (52, 'ICHROMA3', 'iChroma III', NULL, '{"bop": "Cw==", "eop": "HA==", "exch_type": "HL7"}'::jsonb, true),
  (53, 'IRISIQ200', 'IRIS IQ 200', NULL, '{"exch_type": "IRIS"}'::jsonb, true),
  (54, 'MEK7300', 'MEK-7300', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (55, 'APOTI', 'APOTI', NULL, '{"eop": "DQ==", "exch_type": "ASTM"}'::jsonb, true),
  (56, 'RAPID', 'RAPID', NULL, '{"bop": "Ag==", "eop": "BA==", "exch_type": "RAPID"}'::jsonb, true),
  (57, 'EASYRA', 'EASYRA', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (58, 'FUJI', 'FUJI', NULL, '{"bop": "Ag==", "eop": "Aw==", "exch_type": "FUJI"}'::jsonb, true),
  (59, 'IFLASH', 'iFlash', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (60, 'BA200', 'BA200', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (61, 'DIRUI_H100', 'DIRUI H100', NULL, '{"bop": "Ag==", "eop": "Aw==", "exch_type": "TXT"}'::jsonb, true),
  (62, 'Phadia 250', 'Phadia 250', NULL, '{"bop": "Ag==", "eop": "Aw==", "exch_type": "TXT"}'::jsonb, true),
  (63, 'ELYTEPLUS', 'ELYTEPLUS', NULL, '{"bop": "U2FtcGxlIFJlcG9ydA==", "eop": "RW5k", "exch_type": "TXT"}'::jsonb, true),
  (64, 'ERBA', 'ERBA', NULL, '{"exch_type": "ASTM"}'::jsonb, true),
  (65, 'TOUCHPRO', 'TOUCHPRO', NULL, '{"exch_type": "ASTM"}'::jsonb, true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, code = EXCLUDED.code, note = EXCLUDED.note, config = EXCLUDED.config;
